export interface SessionType {
  id?: string; // Optional for new sessions, will be generated by Firestore
  name: string;
  description?: string;
  duration: number;
  [key: string]: any; // Allows any additional properties
}

export interface TodoTask {
  id?: string; // Optional for new tasks, will be generated by Firestore
  title: string;
  description?: string; // Optional
  completed: boolean;
  [key: string]: any; // Allows any additional properties
}

export interface OngoingSession {
  id?: string; // Optional for new sessions, will be generated by Firestore
  sessionTypeId: string; // Reference to SessionType document ID
  startTime: string;
  endTime?: string; // Optional if the session is still ongoing
  [key: string]: any; // Allows any additional properties
}